name: CD - APIM-Rate-Limiting-Policies

on:
  push:
    branches:
      - prod
    paths:
      - apim/policies/rate-limiting/**/release.json
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_apim_policies:
    name: Deploy APIM Policies
    uses: wso2-cicd/wso2-workflows/.github/workflows/cd-apim-rate-limiting-policies.yml@main
    with:
      sourceBranch: prod
      destinationBranch: none
      sourceEnv: prod
      destinationEnv: none
      apiCtlEnv: prod
      openPr: false
    secrets:
      ghBotPat: ${{ secrets.WSO2_GIT_BOT_PAT }}
      ghBotUsername: ${{ secrets.WSO2_GIT_BOT_USERNAME }}
      ghBotEmail: ${{ secrets.WSO2_GIT_BOT_EMAIL }}
      apimAdminUsername: ${{ secrets.WSO2_APIM_PROD_ADMIN_USERNAME }}
      apimAdminPassword: ${{ secrets.WSO2_APIM_PROD_ADMIN_PASSWORD }}