name: CD - APIM-APIs

on:
  push:
    branches:
      - prod
    paths:
      - apim/apis/**/release.json
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_apim_api:
    name: Deploy APIM API
    uses: wso2-cicd/wso2-workflows/.github/workflows/cd-apim-apis.yml@main
    with:
      sourceBranch: prod
      destinationBranch: none
      sourceEnv: prod
      destinationEnv: none
      apiCtlEnv: prod
      createPromotionPr: false
    secrets:
      ghBotPat: ${{ secrets.WSO2_GIT_BOT_PAT }}
      ghBotUsername: ${{ secrets.WSO2_GIT_BOT_USERNAME }}
      ghBotEmail: ${{ secrets.WSO2_GIT_BOT_EMAIL }}
      apimAdminUsername: ${{ secrets.WSO2_APIM_PROD_ADMIN_USERNAME }}
      apimAdminPassword: ${{ secrets.WSO2_APIM_PROD_ADMIN_PASSWORD }}