name: CD - APIM-Rate-Limiting-Policies

on:
  push:
    branches:
      - uat
    paths:
      - apim/policies/rate-limiting/**/release.json
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_apim_policies:
    name: Deploy APIM Policies
    uses: isamauny-wso2/wso2-workflows/.github/workflows/cd-apim-rate-limiting-policies.yml@main
    with:
      sourceBranch: uat
      destinationBranch: prod
      sourceEnv: uat
      destinationEnv: prod
      apiCtlEnv: uat
    secrets:
      ghBotPat: ${{ secrets.WSO2_GIT_BOT_PAT }}
      ghBotUsername: ${{ secrets.WSO2_GIT_BOT_USERNAME }}
      ghBotEmail: ${{ secrets.WSO2_GIT_BOT_EMAIL }}