name: CD - APIM-Mediation-Policies

on:
  push:
    branches:
      - dev
    paths:
      - apim/policies/mediation/**/release.json
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_apim_policies:
    name: Deploy APIM Policies
    uses: isamauny-wso2/wso2-workflows/.github/workflows/cd-apim-mediation-policies.yml@main
    with:
      sourceBranch: dev
      destinationBranch: qa
      sourceEnv: dev
      destinationEnv: qa
      apiCtlEnv: dev
    secrets:
      ghBotPat: ${{ secrets.WSO2_GIT_BOT_PAT }}
      ghBotUsername: ${{ secrets.WSO2_GIT_BOT_USERNAME }}
      ghBotEmail: ${{ secrets.WSO2_GIT_BOT_EMAIL }}
      apimAdminUsername: ${{ secrets.WSO2_APIM_DEV_ADMIN_USERNAME }}
      apimAdminPassword: ${{ secrets.WSO2_APIM_DEV_ADMIN_PASSWORD }}